Merge develop 12
DSI-HUG/dejajs-components pull request #690
Opened 2021-06-05 14:45 UTC by vapkse

2021-06-09 13:14 UTC, ldulary requested changes

2021-06-09 13:14 UTC, ldulary commented on projects/deja-js/component/date-selector/index.ts
>          DejaCircularPickerModule,
encore utile ?

2021-06-09 13:14 UTC, ldulary commented on projects/deja-js/component/tsconfig.lib.prod.json
> +        "emitDecoratorMetadata": false,
t'es sûr ?

2021-06-09 13:14 UTC, ldulary commented on projects/deja-js/component/v2/numeric-stepper/_numeric-stepper-theme.scss
> +@import '~@angular/material/theming';
remplacer @import

2021-06-09 13:50 UTC, vapkse commented on projects/deja-js/component/tsconfig.lib.prod.json
> +        "emitDecoratorMetadata": false,
Pas de json obect mapper dans cette lib, je ne pense pas que la metadat soit utile, par contre elle génère pleins de warnings au build

2021-06-10 08:43 UTC, ldulary approved these changes

2021-06-10 08:43 UTC, merged