feat(): monaco-editor v2 with reactive form support
DSI-HUG/dejajs-components pull request #812
Opened 2022-10-07 14:01 UTC by pdth

small upgrade to use monaco-editor using a reactive form

2022-10-07 14:16 UTC, vapkse requested changes
Le composant doit extends ControlValueAccessor

2022-10-07 14:40 UTC, pdth commented
> Le composant doit extends ControlValueAccessor

MaJ, merci pour la vérification

2022-10-07 15:53 UTC, vapkse requested changes
Faut qu'on cause du husky.js, il y a un truc que je ne comprends pas. Sinon, merci de ne pas committer de node_modules ou de yarn.lock. Les package-lock.json ne devraient pas être commités aussi, car les node-modules n'ont pas changés.

2022-10-10 08:19 UTC, pdth commented
retiré le merge polémique.
d'accord pour voir le husky.js, chez moi ca marche avec et sans dossier '.husky'

2022-10-12 09:52 UTC, vapkse approved these changes

2022-10-12 09:52 UTC, merged